 steps:
 # Build the container image
 - name: 'gcr.io/cloud-builders/docker'
   args: ['build', '-t', 'gcr.io/$PROJECT_ID/sparc-cloud-run:$COMMIT_SHA', './deploy/backend/']
 # Push the container image to Container Registry
 - name: 'gcr.io/cloud-builders/docker'
   args: ['push', 'gcr.io/$PROJECT_ID/sparc-cloud-run:$COMMIT_SHA']
 # Deploy container image to Cloud Run
 - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk' 
   entrypoint: gcloud
   args:
   - 'run'
   - 'deploy'
   - 'sparc-cloud-run'
   - '--image'
   - 'gcr.io/$PROJECT_ID/sparc-cloud-run:$COMMIT_SHA'
   - '--region'
   - 'us-west1'
   - '--allow-unauthenticated'
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: gcloud
    args:
    - 'app'
    - 'deploy'
    - 'cron.yaml'
 images:
 - 'gcr.io/$PROJECT_ID/sparc-cloud-run:$COMMIT_SHA'
